### ISSUE TITLE
provide a way to turn off stepper

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_CircuitPython_Motor#19]
I can't  find away to release the coils on a stepper in motor_featherwing.  Could this be added to the library? Similar to release()  in Adafruit_MotorShield. Thanks!

**Comment by dhalbert** [comment]
We'll try to make it consistent with what we do for #17.

**Comment by ladyada** [comment]
hiya, its now added, call `release()` to turn off all the coils
