### ISSUE TITLE
Add servo examples not dependent on PCA9685

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Motor#25]
A servo can be driven directly from a PWM pin. Add examples for regular servos and continuous servos, something like https://learn.adafruit.com/adafruit-circuit-playground-express/circuitpython-servo.

**Comment by ladyada** [comment]
@kattni wanna write this?

**Comment by ladyada** [comment]
added one here
https://github.com/adafruit/Adafruit_CircuitPython_Motor/pull/27

**Comment by caternuson** [comment]
I think #27 took care of this? If not reopen.
