### ISSUE TITLE
Example should be renamed to include simpletest

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Motor#31]
Example `motor_servo_sweep.py` should be renamed to `motor_servo_sweep_simpletest.py` to fit with CircuitPython library standards.

**Comment by william3031** [comment]
Like this? https://github.com/adafruit/Adafruit_CircuitPython_Motor/pull/32

**Comment by kattni** [comment]
Thanks for doing this! It's close! I've left comments on the PR.

**Comment by williamlai2** [comment]
I've redone it now. Hopefully this works better. I did the file rename in git. https://github.com/adafruit/Adafruit_CircuitPython_Motor/pull/33
