### ISSUE TITLE
PWM output low average voltage problem with Servo motor

### ISSUE THREAD

**Issue by namigaliyev** [adafruit/Adafruit_CircuitPython_Motor#45]
We have an MG996R model Servo motor.
The PWM output from the Coral is only 2.5V peak, and not very strong. We are using the HC4049 model buffer for this. But this doesn't work. We couldn't run our servo motor. Previously we have Raspberry PI 3 Model B and it was working smoothly.

We are following this article.
https://learn.adafruit.com/circuitpython-on-google-coral-linux-blinka/pwm-outputs-servos
We tried the codes in the "Servo Control" section. 
Didn't get errors but nothing happened.
This doesn't work for me.
Do you have an idea to increase the power of the PWM output?
Thanks.

**Comment by ladyada** [comment]
HC4049 are inverter not buffer. if you have more questions about google coral - please post them to google support forum, they will be able to help you and have guides for coral!
