### ISSUE TITLE
Recommend adding DCMotor controller decay mode getter/setter

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/Adafruit_CircuitPython_Motor#53]
Thanks to a wonderful question/assertion from @ZodiusInfuser (thank you), I experimented with a change of DCMotor's default "coasting" (fast) decay mode to "braking" (slow) decay mode. The result was even more significant than adjusting PWM frequencies for expanding the controllable motor speed range. Braking mode also linearized the relationship between throttle and motor speed as well as reducing sensitivity to higher (>500Hz) PWM frequencies. When coupled with a lower PWM frequency such as 25Hz, braking mode increased torque at low motor speeds and contributed to a very low spin threshold.

The braking mode change was successfully tested with TB6612 and DRV8833-based motor controllers (Crickit, MotorWing, and various breakouts), but hasn't been tested on the entire range of Adafruit motor controller boards and discrete h-bridge ICs -- issues aren't anticipated. I placed an order to obtain the rest of the Adafruit motor controller inventory and plan to complete the tests when the devices arrive late next week.

I expect to submit a PR to add a getter/setter to DCMotor to allow switching between braking and coasting modes on a motor-by-motor basis, keeping coasting as the default for compatibility with existing projects. Would like to have a discussion about the UI for the controller decay mode parameter. During testing I've been using:
```python
motor1.decay_mode = 0  # Coasting mode
motor1.decay_mode = 1  # Braking mode
```

![image](https://user-images.githubusercontent.com/29906257/110042595-dc9ee080-7cfa-11eb-90fd-7f32b15a52d0.png)
Result of mode comparison test at 25Hz. Note the improved spin threshold (speed = red line)  and overall linearity of speed versus throttle (shown as PWM Equivalent Voltage).

**Comment by CedarGroveStudios** [comment]
<img width="635" alt="Screen Shot 2021-03-04 at 3 17 28 PM" src="https://user-images.githubusercontent.com/29906257/110044023-4ddf9300-7cfd-11eb-8aee-75988104cdd1.png">
Result of mode comparison test at 1600Hz (the MotorWing/Shield's default PWM frequency). Note the improved spin threshold (1.6v versus 3.3v).

**Comment by CedarGroveStudios** [comment]
Another alternative to ponder would be to eliminate the need for a mode selection parameter by changing the default mode from coasting to braking as recommended by TI in the DRV8871 data sheet. Discrete h-bridges wouldn't be impacted by the change. Modern controller chips like DRV8833, DRV8871, and TB6612 would see dramatically improved performance, but legacy projects with code to linearize the throttle/speed curve may experience a change in speed behavior and battery consumption. 

<img width="1481" alt="DRV8871_note" src="https://user-images.githubusercontent.com/29906257/110365561-06f1e600-7ffa-11eb-85d5-1d6c29d518f9.png">

**Comment by ladyada** [comment]
sure, wanna send over a PR?

**Comment by ZodiusInfuser** [comment]
@CedarGroveStudios My view is both modes should be available, as there could be the odd cases where for example you've got a motor spinning and want it to coast to a stop. That does however require a change to the current behavior though, which as we discussed privately does coasting for driving, and braking for stopping.

**Comment by CedarGroveStudios** [comment]
@ZodiusInfuser, @ladyada:  I propose that we 1) add the decay_mode getter/setter while keeping coasting mode as the default and 2) change the throttle value interpretation for braking and coasting to be more consistent with modern motor controllers. Although it may impact existing implementations, I believe it makes more sense for a throttle value of zero to cause braking to that speed; a throttle value of _None_ is more logically the high-impedance coasting mode. In either case, discrete h-bridge implementations should see no operational change. Thoughts?

![image](https://user-images.githubusercontent.com/29906257/110381368-36aae900-800e-11eb-8998-cb9df06fa9ed.png)

**Comment by CedarGroveStudios** [comment]
@ladyada I'm planning to submit a PR after testing with all the Adafruit boards and the pertinent portion of the motor collection. Have to pace this with my maker budget limitations, so it may take a week or two to complete as the orders arrive. I'll rewrite the learning guide after the PR is merged.
