### ISSUE TITLE
Add support for relative angle changes for servo?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Motor#55]
To be able to move +/- some angle amount from current location. Maybe useful?
https://forums.adafruit.com/viewtopic.php?f=60&t=178120

Currently can only set absolute angles.
```python
servo.angle = 90
```

**Comment by ladyada** [comment]
in theory, if angle is both a getter/setter - you could += or -=?

**Comment by caternuson** [comment]
:facepalm: not theory. simple fact. tested and works.

**Comment by ladyada** [comment]
haha rad!
