### ISSUE TITLE
Frequency of PCA9685 can't be set on a per channel basis

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Motor#68]
Re this thread:
https://forums.adafruit.com/viewtopic.php?t=197676

PR #67 undid the fix done with PR #13 and reintroduced issue #12.

**Comment by tekktrik** [comment]
Whoops, I'll take this.  I'll see if there's a way to get both.

**Comment by tekktrik** [comment]
They should be able to get the new version on PyPI now!
