### ISSUE TITLE
Motor kit / motor issues

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_CircuitPython_Motor#75]
Rather strange problem: Feather can't seem to process "from adafruit_motorkit import MotorKit". So far I have checked file names, versions, reinstalled motorkit and motor libraries, ensured they are in the right destination, and tried calling them with "import adafruit_motor" and "import adafruit_motorkit", both of which worked properly. Had little to no trouble getting files for the OLED to work and I followed the same steps, as well as closely following the guide: https://learn.adafruit.com/adafruit-stepper-dc-motor-featherwing/circuitpython. Needless to say this is preventing me from running the stepper motor I'm working with.

**Comment by caternuson** [comment]
Please post the full text of any error message(s). Or provide more details on what "can't process" means.

**Comment by ghost** [comment]
Went into the REPL to get an error message. 


<img width="410" alt="image" src="https://github.com/adafruit/Adafruit_CircuitPython_Motor/assets/100823833/52e6f5ac-99fc-456e-83c8-8947daa68002">

**Comment by caternuson** [comment]
Probably just a library install issue.

There should be a file named `adafruit_motokit.mpy` in your `CIRCUITPY/lib` folder.

There should **NOT** be any folders named `adafruit_motorkit` in your `CIRCUITPY/lib` folder.

**Comment by ghost** [comment]
I cleaned the library and did another fresh install, finally got it working. Thanks for your help.
